- 别人的贱是学出来的，你是天生的。
- 你说你天生丽质，我看你就是天生贱制。
- 你这人没啥特出众，就是面子够坚固。
- 一闪一闪亮晶晶，我说你就是傻逼。
- 别动不动就爆粗口，你把你妈揣兜了随口就说。
- 之前以为你是颓废，原来你是报废。
- 哎呦喂，这狗还会说话，奇迹啊！
- 拿你当人的时候，你尽量装得像点好吗？
- 你的牙齿别以为很白，不过也可以拿来当做高露洁的反面例子是最适合不过了。
- 你的智商太低，就别秀，秀多了就秀逗了。
- 看到你跑步的姿势，我顿悟，猪原来是这样跑的。
- 我觉得你特适合卡通片，卡通片里面的老巫婆！
- 别用这种眼神看着我，我怕得红眼病。
- 笑什么笑？笑的那样子跟得了糖尿病喝糖尿似的。
- 你漂亮到连大象看到你都会在三秒内流鼻血。
- 真是脑残者无药可医啊！
- 说你是脑残都是提高了你的档次。
- 你就是根黄瓜，还是凸点型的，就是欠拍啊！
- 你每天做面膜，长得丑不是你的错，但长的这么丑就太过分了。
- 世上唯你能把贱表演的如此精湛，别以为你头上顶的是铁锅就比傻帽强。
- 你带刀了吗？我捅死你！
- 脑子没事多装点东西，别连点水都没有。
- 装的像个出家人，把自己说的是个神。
- 我老远就能闻到你的臭味，真是太恶心了。
- 你的愚蠢总是蠢得那么有创造力。
- 见识短的，脸盆里撒个尿就以为见到了大海。
- 你这副娘娘腔样，就连我家的猪狗都看不上你，你仍是趁早了结了吧！
- 没事你就扯点卫生纸擦擦你的鼻涕吧。
- 不怕牛逼的对手，就怕像猪一样的队友。
- 猛地一看你不怎么样，仔细一看还不如猛的一看。
- 如果你有本事，现在就不会在这啃泥巴了。
- 你好意思在这里唧唧歪歪的炫耀你的无知吗？
- 你说你腰粗，我想弱弱的问句“你有腰吗？”
- 你以为你是帅哥啊，你简直就是一怪兽。
- 你长的也忒朦胧了点吧，一脸的模糊不清啊！
- 脸长的跟矿泉水瓶让人踹瘪了似的，你的头是被驴踢过还是被啃过啊？。
- 不当坏人，真浪费了你这双鬼鬼祟祟的眼。
- 你知道你为什么长成这样么，遗传。
- 百度搜不到你，试试搜狗。
- 你三观很正，就可惜五官不行。
- 我掐指一算，你五行里缺心眼。
- 您配钥匙吗？您配吗？您配几把？
- 是人三分贱你却七分贱。为什么呢？
- 我是没有锅，有锅早就把你给炖了。
- 一个个都在打∠是吧
- 你也配？我笑了
- 你真聪明，居然还知道自己是个人。
- 我不是草船，你的贱别往我这发。
- 狗应该给你拜把子，就你这找屎能力，天下没有饿不死的狗了，狗连刨个坑都不用，你自己就把他挖上来了
- 真羡慕你的皮肤，保养的这么厚。
- 你是什么牌子塑料袋，这么能装。
- 你妈给你这张脸就是为了防早恋。
- 你是古玩城老板吗？见谁都叫宝贝。
- 其实你不讨厌，可惜就是全无用处。
- 完了，你也不理我，我成狗不理了！
- 和你接触的时间越长，我就越喜欢狗。
- 你是阿基米德的后代吧，这么会抬杠。
- 你的脸皮太厚，厚到地球都无地自容。
- 你别看你穿的很危险，但你长得很安全。
- 认二郎神当主人是不是把你高兴坏了？
- 你复杂的五官也掩饰不了你朴素的智商。
- 我不是看不起你，而是压根就懒得理你。
- 抽空一起去吃鱼吧，我看你挺会挑刺的。
- 你不去当厨子可惜了，甩锅甩的那么厉害。
- 见到你之后，我才发现，丑可以这么具体。
- 上帝把智慧洒满人间，唯独给你撑了把伞。
- 智商是个好东西，我有，他有，希望你也有。
- 多去晒晒太阳，晒黑点就没人骂你是白痴了。
- 我是快递员，我说你是小件货你就是小件货。
- 别把自己想的太伟大，没了你，地球照样转。
- 我长的是不好看，但也没你那么随心所欲啊。
- 你们家都是你做饭吧，我看你挺会添油加醋的。
- 眼睛是心灵的窗户，我觉得你的窗户该擦擦了。
- 古话说得好，吃亏是福，那么我祝你福如东海。
- 别人给你留面子的前提，是你首先得有脑子啊！
- 对你越客气，就证明我，越不想和你有任何关系。
- 你的高智商，绝对适合晚上数月亮，白天数太阳。
- 我至今无法相信你会是十万个精子里跑的最快的。
- 你可以不要别人给你的脸，但你不能不要自己的脸。
- 我们总不能让所有人都满意，因为不是所有人都是人。
- 你爸妈肯定很幽默吧，要不然怎么生了个笑话出来？
- 我瞅着你那样就十分纳闷，世上怎会有你这样的非生物！
- 我没认识你之前，我真没发现原来我有以貌取人这毛病。
- 不要太在意某些人说的话，因为他们有嘴，但不一定有脑。
- 如果你的丑陋可以发电的话，全世界的核电厂都可以停摆。
- 别总拿自己饱经风霜的脸说事，美的不突出，丑的不别致。
- 你是我见过的容量最大的铅笔盒了，装那么多笔你不累吗？
- 你长得就和二维码似的，不扫一扫还真不知道是个什么东西。
- 如果全世界都不要你了，记得来找我，我认识好几个人贩子。
- 唱歌不着调是你五音不全，说话不着调是不是你大脑不健全啊！
- 从小我的妈妈就告诉我做人要有礼貌，我多希望你也能有个妈妈。
- 我不在乎强扭的瓜甜不甜，只要扭下来，扭下来我就开心了我啊！
- 你不说话还能让人有点幻想，一张口说话那一点点幻想都给破灭了。
- 僵尸兴奋地打开你的头盖骨，失望地走开了，旁边的屎壳郎眼前一亮。
- 我管你圈子有多大，人脉有多广，在我面前，麻烦你，好好说话，说我能听得懂的人话。