bangroups:
- 2132321
- 879886836
banuser:
- 1
- 4564949845
botoff:
- 6994557
- 623265372
defaultModel:
  modelSelect:
  - voiceModel/nene/1374_epochsm.pth
  - voiceModel/nene/config.json
  speaker: 2
moderate:
  apiKeys:
    '699455559': fadfasfasf
  banTime: 300
  banWords:
    '60844343475':
    - 斯卡蒂
  groups:
    '69945555439': 1
  threshold: 40
superBlGroups:
- 623265372
trustGroups:
- 699455559
