#å•ç‹¬åŠŸèƒ½å¼€å…³
botè‡ªèº«è®¾ç½®:
  FordMesMenu: false #æ˜¯å¦ä»¥èŠå¤©è®°å½•å½¢å¼å‘é€èœå•
aiç»˜ç”»:
  æ¥å£1: false    #å¤§æ¦‚æ˜¯è·‘è·¯äº†
  æ¥å£2: false    #æ—¥å¸¸å¯„
  æ¥å£3: true     #å·®ä¸å¤š
  æ¥å£4: true
  æ¥å£5: true
  æ¥å£6: true    #(è¿˜è¡Œï¼Œåªæ”¯æŒè‹±æ–‡prompt)
  modelscopeSD: True  #modelscopeé€†å‘aiç»˜å›¾ï¼Œè¾ƒä¸ºç¨³å®š
  sdæ¥å£: true   #anything v3
  aié‡ç»˜: false  #ç›®å‰åº”è¯¥æ˜¯ä¸å¯ç”¨çš„
  aié‡ç»˜2: false #åŒä¸Š
  sdé»˜è®¤å¯åŠ¨æ¨¡å‹: obsessionIllustrious_v30.safetensors
  no_nsfw_groups: [111,222,333] #ç¦æ­¢è‰²å›¾çš„ç¾¤å·
  positive_prompt: (((best quality))),(((ultra detailed))),(((masterpiece))),illustration,Extreme
    detail expression,Ultra High Definition,Maximum Detail Display,Hyperdetail,Clear
    details,Amazing quality,Super details,Unbelievable,HDR,16K,details,The most authentic,Glossy
    solid color
  negative_prompt: nsfw, paintings, sketches, worst quality, low quality, normal quality,
    lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black
    skin, skin spots, skin blemishes, age spot, glans, disabled, distorted, bad anatomy,
    morbid, malformation, amputation, bad proportions, twins, missing body, fused
    body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed,
    long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue,
    strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands,
    fused hands, connected hand, bad hands, wrong fingers, missing fingers, extra
    fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs,
    more than two legs, bad feet, wrong feet, extra feets,
é»‘ç¥è¯wiki: 
  æŠ€èƒ½æ‹›å¼: False
  ä»¥èŠå¤©è®°å½•å½¢å¼å‘é€: True
å°åŠŸèƒ½:
  å‘ç—…: true
ç‚¹æ­Œ:
  ä¸‹è½½é“¾æ¥: false #ç‚¹æ­Œé™„å¸¦ä¸‹è½½é“¾æ¥
  musicToVoice: true        #æ˜¯å¦ä»¥è¯­éŸ³æ–¹å¼ç‚¹æ­Œ
å›¾ç‰‡ç›¸å…³:
  allowPic: True            #æ˜¯å¦å¯ç”¨å‘å›¾åŠŸèƒ½
  onlyTrustUserR18: True    #ä»…å…è®¸ä¿¡ä»»ç”¨æˆ·ä½¿ç”¨r18
  r18Pic: True              #å¯¹æ‰€æœ‰äººå¼€æ”¾æ¶©å›¾r18æ¨¡å¼
  grayPic: True             #å›¾ç‰‡è½¬ç°åº¦å›¾ï¼Œé™ä½è¢«åå‡ ç‡
  withPic: True            #æ˜¯å¦å±•ç¤ºå›¾ç‰‡é¢„è§ˆï¼Œä¸å»ºè®®å¼€ï¼Œå®¹æ˜“è¢«å
  InternetMeme: False       #æ˜¯å¦å¯ç”¨ç½‘ç»œMemeï¼ˆè‹±æ–‡memeï¼‰
  watchPrefix: "/"          #â€œçœ‹çœ‹â€æŒ‡ä»¤çš„å‰ç¼€
  wifePrefix: "/"          #â€œé€ç¾¤å‹â€æŒ‡ä»¤çš„å‰ç¼€
è¿åŠ¿&å¡”ç½—:
  lockLuck: false           #æ˜¯å¦é”å®šè¿åŠ¿ç­‰åŠŸèƒ½çš„ç»“æœ
  isAbstract: false          #æ˜¯å¦å¯ç”¨æŠ½è±¡å¡ç»„
JMComic:            #ç¦æ¼«ç›¸å…³åŠŸèƒ½è®¾ç½®
  enable: True     #å…¨å±€å¼€å…³
  onlyTrustUser: False #æ‰“å¼€åï¼Œä»…masteræˆæƒç”¨æˆ·å¯ç”¨
  URLSource: 1 #ä½¿ç”¨çš„ç½‘ç›˜ï¼Œ0ä¸ºè“å¥äº‘ï¼Œ1ä¸ºfile.ioï¼Œ2ä¸ºä¸å¯ç”¨ã€‚è“å¥äº‘éœ€é…ç½®cookieï¼Œfile.ioå¯èƒ½éœ€è¦é…ç½®proxy
  previewPages: 6  #éªŒè½¦é¢„è§ˆé¡µæ•°
  sendFile: False #ä»¥æ–‡ä»¶å½¢å¼å‘é€(å¯èƒ½è¢«åå’Œå°å·)
  autoClearPDF: True #ä¸‹è½½åè‡ªåŠ¨æ¸…é™¤pdf
  savePath: "./data/pictures/benzi"  #ä¸‹è½½ä¸ºpdfçš„é»˜è®¤ä¿å­˜è·¯å¾„
ç¢§è“æ¡£æ¡ˆ:
  è®¢é˜…ä¸æ¨é€: True   #ä¸ºå¼ºè¿«ç—‡æä¾›çš„å¼€å…³ï¼Œå…³é—­åä¸ä¼šå†æ£€æŸ¥ç¢§è“æ¡£æ¡ˆä¸‰æœè®¢é˜…æ›´æ–°
bç«™ç›¸å…³åŠŸèƒ½:
  ç›´æ’­è®¢é˜…: True    #åŒä¸Šï¼Œbç«™ç›¸å…³åŠŸèƒ½ç°åœ¨ä¸å¤šï¼Œä»¥ååŠ 
æ¼‚æµç“¶:
  enable: True    #æ˜¯å¦å¯ç”¨æ¼‚æµç“¶åŠŸèƒ½
  pushcomments: True #ç”¨æˆ·çš„æœ‰è¯„è®ºæ—¶æ˜¯å¦å‘ç”¨æˆ·æ¨é€é€šçŸ¥
  sensor: False   #æ˜¯å¦å¯ç”¨å®¡æ ¸åŠŸèƒ½(æš‚æ—¶ä¸å¯ç”¨)
scheduledTasks:    #å…¶ä»–å®šæ—¶ä»»åŠ¡æ¨¡å—çš„å†…å®¹ä¼šé™†ç»­è½¬åˆ°è¿™é‡Œ
  morning:         #æ™¨é—´æ¨é€
    enable: true  #å‘ä¿¡ä»»ç”¨æˆ·æ¨é€å¤©æ°”ä¿¡æ¯
    text: "æ—©ä¸Šå¥½ï¼Œè¿™é‡Œæ˜¯ä»Šå¤©çš„å¤©æ°”"  #å¦‚å¯ç”¨aiReplyCoreï¼Œæ­¤é¡¹å°†è¢«aiæ›¿ä»£
    time: 8/3      #æ¨é€æ—¶é—´
    trustThreshold: 3 #ä¿¡ä»»ç”¨æˆ·çš„è®¢é˜…æ•°é˜ˆå€¼(ç­¾åˆ°å¤©æ•°)ï¼Œä½äºæ­¤å€¼çš„ç”¨æˆ·å°†ä¸ä¼šè¢«æ¨é€
    onlyTrustUser: True  #ä»…å‘ä¿¡ä»»ç”¨æˆ·æ¨é€
  bangumi:         #bangumiæ¨é€
    enable: True
    text: "æ™šä¸Šå¥½ï¼Œè¿™é‡Œæ˜¯ä»Šå¤©çš„bangumiæ¨é€"
    time: 19/16
  astronomy:       #nasaå¤©æ–‡æ¨é€
    enable: True
    text: "ä»Šæ—¥nasaå¤©æ–‡æ¨é€"
    time: 18/59
  constellation:   #æ˜Ÿåº§æ¨é€
    enable: True
    text: æ‚é±¼æ€ä¹ˆè¿˜ä¿¡æ˜Ÿåº§è¿™ç§ä¸œè¥¿å•Š
    time: 16/30
  danxiangli:      #å•å‘å†
    enable: true
    text: ä»Šæ—¥å•å‘å†
    time: 19/2
  moyu:            #æ‘¸é±¼äººæ—¥å†
    enable: true
    text: çœŸæ²¡ç”¨å•Šï¼Œåˆåœ¨æ‘¸é±¼äº†å§ï¼Œæ‚é±¼â¤
    time: 17/30
  news:            #æ–°é—»
    enable: true
    text: æ—©ä¸Šå¥½æ‚é±¼â¤ï¼Œè¿™é‡Œæ˜¯ä»Šå¤©çš„æ–°é—»
    time: 8/2
  steamadd1:       #å…è´¹æ¸¸æˆæç¤º
    enable: true
    text: æ‚é±¼â¤æ¥ç™½å«–æ¸¸æˆäº†
    time: 12/2
  goodnight:       #æ™šå®‰æç¤º
    enable: true
    text: æ™šå®‰æ‚é±¼â¤ï¼Œç¥ä½ æœ‰ç¾å¥½çš„ä¸€å¤©ï¼ #å¼€å¯aiReplyCoreåï¼Œæ­¤é¡¹å°†è¢«aiæ›¿ä»£
    time: 22/21
    trustThreshold: 3 #ä¿¡ä»»ç”¨æˆ·çš„è®¢é˜…æ•°é˜ˆå€¼ï¼Œä½äºæ­¤å€¼çš„ç”¨æˆ·å°†ä¸ä¼šè¢«æ¨é€
    onlyTrustUser: True  #ä»…å‘ä¿¡ä»»ç”¨æˆ·æ¨é€
  bingEveryDay: #ä»Šæ—¥bing
    enable: true
    text: ""
    time: 10/2
  nightASMR:
    enable: true
    text: å¬å®Œå°±èµ¶ç´§ç¡è§‰å§~ç¥ä½ å¥½æ¢¦ï¼(â‰§â–½â‰¦*)
    time: 22/35
æ£€æµ‹:
  å¥¶é¾™æ£€æµ‹: false
  å¥¶é¾™æ’¤å›: true
  å¥¶é¾™ç¦è¨€: true
  éª‚å¥¶é¾™:
  - å¥¶é¾™æ˜¯ä½ å ï¼Ÿè¿™ä¹ˆå–œæ¬¢å‘å¥¶é¾™ï¼Ÿ
  doroæ£€æµ‹: false
  doroæ’¤å›: true
  doroç¦è¨€: true
  éª‚doro:
  - doroæ˜¯ä½ ğŸ´ï¼Ÿè¿™ä¹ˆå–œæ¬¢å‘ä½ ğŸ´çš„é—ç…§ï¼Ÿ #è‡ªå·±æ·»åŠ 
  - ç²‰è‰²å¥¶é¾™
  - å”
