noResMatch:    #除去艾特内容，与这些关键词 完全匹配 的消息，将不会触发ai回复
  - 周易
  - 天文
  - 诗经
  - 摸鱼
  - 新闻
  - 彩色小人
  - 原神
  - 查询
  - 方舟十连
  - 运势
  - 今日塔罗
  - 星铁十连
  - 角色
  - 可用角色模板
  - 星座
  - 帮助
  - 群列表
  - 菜单
  - 功能
  - 开始对话
  - 退出
  - /clear
startswith: #以这些开头的，带艾特的指令将不会触发ai回复
  - 支付宝到账
  - /sbg
endswith:   #以这些结尾的，带艾特的指令将不会触发ai回复
  - xxxxx
Regular:    #正则表达式，如匹配则不会触发ai回复
  - '(\d+)张(\w+)'
