memberJoin: #加群欢迎
  - \n欢迎哦，这里是botName(*≧︶≦))(￣▽￣* )ゞ🥰\n项目源地址与文档：https://github.com/avilliai/Manyana\n也可以发送@我 帮助 以查看功能列表\n💢请勿滥用本机器人💢
  - 欢迎
sendTemp:   #加群之后向加群者私聊发送消息
  - 你好哦
  - 你好
muteEvent:
  - '%被动% 被%主动% 禁言了，好似喵🥴🥴'
  - '%被动% 被禁言了，好可怜🥴🥴'
UnMute:   #解除禁言事件
  # Bot 被管理员解禁时的回复
  # 变量: %主动% (解禁操作人)
  botUnmuteMessage:
    - '我自由啦！感谢%主动% 大人 🥵🥵'
    - 解除禁言了呢
  memberUnmuteMessage:
    - '%被动% 你的禁言解除了哦，快谢谢%主动% 吧🥳'
  # 全体解禁时的回复
  # 变量: %主动% (解禁操作人)
  groupMuteAllRelease: 欸，解封了吗
quitGroup:   #退出群的提示
  # 变量: %主动% (踢人操作人), %被动% (被踢出的前群员)
  kickMessage:
    - '有人被%主动% 移出群聊了.....😠'
    - '%被动% 被%主动% 移出群聊😠'
  # 有人主动退群时的回复
  # 变量: %主动% (退出的前群员)
  quitMessage:
    - '%主动% 悄悄离开了🥺'
